# Generated by Django 5.2.3 on 2025-07-01 16:36

import authentication_handler.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('years_experience', models.CharField(blank=True, choices=[('', 'Select years of experience'), ('0-1', '0-1 years'), ('2-5', '2-5 years'), ('6-10', '6-10 years'), ('11-15', '11-15 years'), ('16-20', '16-20 years'), ('20+', '20+ years')], max_length=20)),
                ('awards', models.TextField(blank=True, help_text='Notable awards, certifications, or citations')),
                ('specialty', models.CharField(blank=True, choices=[('', 'Select specialty'), ('first_time_buyers', 'First-time Home Buyers'), ('luxury_homes', 'Luxury Homes'), ('investment_properties', 'Investment Properties'), ('downsizing', 'Downsizing/Senior Living'), ('new_construction', 'New Construction'), ('commercial', 'Commercial Real Estate'), ('rural_farm', 'Rural/Farm Properties'), ('foreclosures', 'Foreclosures/REO'), ('relocation', 'Relocation Services'), ('military_va', 'Military/VA Loans')], max_length=100)),
                ('shortest_sale', models.CharField(blank=True, help_text="Shortest time to sell a listing (e.g., '7 days')", max_length=100)),
                ('highest_sale', models.CharField(blank=True, help_text="Highest sale closed (e.g., '$2.5M')", max_length=100)),
                ('avg_days_on_market', models.CharField(blank=True, help_text='Average days on market for listings', max_length=100)),
                ('mission', models.TextField(blank=True, help_text="Mission or 'Why' for doing real estate")),
                ('value_proposition', models.TextField(blank=True, help_text='Unique value proposition')),
                ('selling_style', models.CharField(blank=True, choices=[('', 'Select selling style'), ('consultative', 'Consultative Approach'), ('aggressive_marketing', 'Aggressive Marketing'), ('white_glove', 'White-Glove Service'), ('data_driven', 'Data-Driven Strategy'), ('relationship_focused', 'Relationship-Focused'), ('technology_forward', 'Technology-Forward'), ('full_service', 'Full-Service Support')], max_length=50)),
                ('testimonial_1', models.TextField(blank=True, help_text='Client testimonial or success quote')),
                ('testimonial_2', models.TextField(blank=True, help_text='Second client testimonial or success quote')),
                ('community_ties', models.TextField(blank=True, help_text='Neighborhood ties and community involvement')),
                ('headshot', models.ImageField(blank=True, null=True, upload_to=authentication_handler.models.agent_headshot_path)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=authentication_handler.models.company_logo_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Profile',
                'verbose_name_plural': 'Agent Profiles',
            },
        ),
    ]
