# Generated by Django 5.2.3 on 2025-07-07 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_handler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Property address', max_length=500)),
                ('package_name', models.CharField(default='Professional', max_length=100)),
                ('analysis_content', models.TextField(help_text='HTML content of the analysis')),
                ('analysis_model', models.CharField(default='sonar', max_length=50)),
                ('api_response', models.JSONField(help_text='Full API response from Perplexity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Analysis',
                'verbose_name_plural': 'Property Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
