# Generated by Django 5.2.3 on 2025-07-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_handler', '0002_propertyanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='testimonial_3',
            field=models.TextField(blank=True, help_text='Third client testimonial or success quote'),
        ),
    ]
