# Generated by Django 5.2.3 on 2024-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_handler', '0003_agentprofile_testimonial_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyanalysis',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe payment intent ID', max_length=200, null=True),
        ),
    ] 