# Generated by Django 5.2.3 on 2025-07-14 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_handler', '0004_propertyanalysis_payment_intent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAnalysisShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_by_name', models.CharField(help_text='Full name of person who shared', max_length=200)),
                ('recipient_email', models.EmailField(help_text='Email address of recipient', max_length=254)),
                ('share_message', models.TextField(blank=True, help_text='Personal message included with share')),
                ('share_link', models.URLField(help_text='Generated shareable link')),
                ('times_shared', models.PositiveIntegerField(default=1, help_text='Number of times shared to this email')),
                ('times_viewed', models.PositiveIntegerField(default=0, help_text='Number of times viewed by this recipient')),
                ('first_shared_at', models.DateTimeField(auto_now_add=True)),
                ('last_shared_at', models.DateTimeField(auto_now=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('property_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='authentication_handler.propertyanalysis')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Analysis Share',
                'verbose_name_plural': 'Property Analysis Shares',
                'ordering': ['-last_shared_at'],
                'unique_together': {('property_analysis', 'recipient_email')},
            },
        ),
        migrations.CreateModel(
            name='SharedAnalysisView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='authentication_handler.propertyanalysisshare')),
            ],
            options={
                'verbose_name': 'Shared Analysis View',
                'verbose_name_plural': 'Shared Analysis Views',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
