# Generated by Django 5.2.3 on 2025-07-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_handler', '0006_add_agent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='years_experience',
            field=models.CharField(blank=True, help_text="Years of experience in real estate (e.g., '5 years', '10+ years')", max_length=50),
        ),
    ]
